### ISSUE TITLE
[FR] Support for multiple repos in the same site? (like https://git.suckless.org)

### ISSUE THREAD

**Issue by xplshn** [picosh/pgit#4]

**Comment by neurosnap** [comment]
Hi!  I recently added some support for multiple repos.

https://github.com/picosh/pgit?tab=readme-ov-file#with-multiple-repos

**Comment by xplshn** [comment]
Oh, great! That's lovely!

I was thinking perhaps it'd be best to be able to have a config in a directory and just run `pgit` without any arguments to have it update/create the files of the static site

**Comment by neurosnap** [comment]
That's a good though and my original implementation did use a config file.  I didn't want `pgit` to be in charge of the root index file and was hoping this would be easier to run since it doesn't require a config file.

Let me know how it goes.

**Comment by xplshn** [comment]
Perhaps using a struct-based cli library and config library would make things easier.
I can certainly recommend https://github.com/goccy/go-yaml, perhaps TOML support too. I personally would use https://github.com/fred1268/go-clap + g-yaml to offer both a CLI and TOML interface to the program.

In one of my programs I have:
![image](https://github.com/user-attachments/assets/4a53245b-ecb1-4f89-96b2-dd6022e05239)
